version: '3.8'
services:
  postgres:
    image: postgres:13.2-alpine
    container_name: database
    ports:
      - 5432:5432
    expose: 
      - 5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:5.1
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5433:80
volumes:
  postgres_volume: